"""Framework-independent financial domain."""

from app.domain.analysis import (
    AnalysisValuation,
    AnalysisValuationPosition,
    AnalysisWindow,
    PortfolioAnalysisReport,
)
from app.domain.analytics import (
    ConcentrationComponent,
    ConcentrationSummary,
    HistoricalAnalytics,
    HistoricalSeriesPoint,
    LabelledMatrix,
    PerformanceSummary,
    calculate_historical_analytics,
    concentration,
)
from app.domain.catalog import AssetCatalog, CurrentUniverseProvider, UniverseSnapshot
from app.domain.conventions import (
    DEFAULT_FINANCIAL_CONVENTIONS,
    AlignmentPolicy,
    FinancialConventions,
    MissingDataPolicy,
    PriceField,
    ReturnConvention,
    ReturnFrequency,
)
from app.domain.errors import (
    DomainValidationError,
    ExternalDataUnavailableError,
    MarketDataValidationError,
    OptimizationSolverError,
)
from app.domain.market_data import (
    AssetPriceSeries,
    DataProvenance,
    MarketDataProvider,
    PriceHistory,
    PriceObservation,
)
from app.domain.models import (
    Asset,
    Currency,
    InvestmentUniverse,
    Money,
    Portfolio,
    PortfolioWeights,
    Position,
    TimeHorizon,
    TimeHorizonUnit,
)
from app.domain.optimization import (
    OPTIMIZATION_TOLERANCE,
    AlignedReturnSample,
    ExpectedReturnEstimator,
    ExpectedReturnSignal,
    HistoricalMeanEstimator,
    HistoricalSampleRiskEstimator,
    OptimizationConstraints,
    OptimizationRequest,
    OptimizationResult,
    PortfolioMetrics,
    PortfolioOptimizer,
    RiskEstimate,
    RiskEstimator,
    SolverDiagnostics,
    evaluate_portfolio,
)
from app.domain.universe import (
    SP500_BENCHMARK_ASSET_ID,
    SP500_BENCHMARK_NAME,
    SP500_UNIVERSE_ID,
    MarketUniverseProvider,
)
from app.domain.valuation import PortfolioValuationSnapshot, ValuationLineItem

__all__ = [
    "DEFAULT_FINANCIAL_CONVENTIONS",
    "OPTIMIZATION_TOLERANCE",
    "SP500_BENCHMARK_ASSET_ID",
    "SP500_BENCHMARK_NAME",
    "SP500_UNIVERSE_ID",
    "AlignmentPolicy",
    "AlignedReturnSample",
    "AnalysisValuation",
    "AnalysisValuationPosition",
    "AnalysisWindow",
    "AssetCatalog",
    "AssetPriceSeries",
    "Asset",
    "Currency",
    "ConcentrationComponent",
    "ConcentrationSummary",
    "CurrentUniverseProvider",
    "DataProvenance",
    "DomainValidationError",
    "ExternalDataUnavailableError",
    "ExpectedReturnEstimator",
    "ExpectedReturnSignal",
    "FinancialConventions",
    "HistoricalAnalytics",
    "HistoricalMeanEstimator",
    "HistoricalSampleRiskEstimator",
    "HistoricalSeriesPoint",
    "InvestmentUniverse",
    "LabelledMatrix",
    "MarketUniverseProvider",
    "MarketDataProvider",
    "MarketDataValidationError",
    "MissingDataPolicy",
    "Money",
    "OptimizationConstraints",
    "OptimizationRequest",
    "OptimizationResult",
    "OptimizationSolverError",
    "Portfolio",
    "PortfolioAnalysisReport",
    "PortfolioMetrics",
    "PortfolioOptimizer",
    "PortfolioWeights",
    "PortfolioValuationSnapshot",
    "Position",
    "PriceField",
    "PriceHistory",
    "PriceObservation",
    "PerformanceSummary",
    "ReturnConvention",
    "ReturnFrequency",
    "RiskEstimate",
    "RiskEstimator",
    "SolverDiagnostics",
    "TimeHorizon",
    "TimeHorizonUnit",
    "UniverseSnapshot",
    "ValuationLineItem",
    "calculate_historical_analytics",
    "concentration",
    "evaluate_portfolio",
]
